### ISSUE TITLE
[ Week03 ] 자료들을 리드미에 작성 후 PR링크 제출 ( 채택할 기본 패키지 구조, 기술 스택 등 )

### ISSUE THREAD

**Issue by nashs789** [nashs789/hhplus-concert-server#14]
## ✨ Task

- [ ] README 작성
- [ ] 과제 PR 작성
- [ ] 기본 패키지 구조 구성
- [ ] 기술 스택 정리
