### ISSUE TITLE
[ Week05 ] 결제 API 구현

### ISSUE THREAD

**Issue by nashs789** [nashs789/hhplus-concert-server#21]
## ✨ Task

- [ ] 결제 API 구현
- [ ] 결제 예외 처리
- [ ] 결제 유효성 검사
