### ISSUE TITLE
[ Step05 ] 시나리오 선정 및 프로젝트 Milestone 제출

### ISSUE THREAD

**Issue by nashs789** [nashs789/hhplus-concert-server#9]
## ✨Task

- [X] 주차별 작업 목록 및 기간 설정
- [X] Github milestone 작성
- [X] Github project timeline 작성
- [X] 작성한 milestone 에 해당하는 Issue 발행
